"""Game-ready output: scaled PNGs, spritesheets with metadata, GIF, and
palette/Aseprite interop."""

import os
import json

import pxa
import imaging
import render
import anim
import palettes


def png(doc, out_dir, scales=(1, 2, 4), frame=None, background=None, prefix=None):
    name = prefix or doc.meta.get("name", "sprite")
    written = []
    frames = [doc.frame(frame)] if frame else doc.frames
    for f in frames:
        for s in scales:
            suffix = "" if len(frames) == 1 else "_%s" % f.name
            path = os.path.join(out_dir, "%s%s%s.png" % (name, suffix,
                                                         "" if s == 1 else "@%dx" % s))
            img = render.render_frame(doc, f, s, background=background)
            pxa.write_png(path, img)
            written.append(path)
    return written


def spritesheet(doc, out_path, columns=None, padding=0, background=None, meta_path=None):
    n = len(doc.frames)
    cols = columns or n
    rows = (n + cols - 1) // cols
    w, h = doc.width, doc.height
    cw, ch = w + padding, h + padding
    sheet = imaging.new_image(cols * cw - padding, rows * ch - padding,
                              background or (0, 0, 0, 0))
    frames_meta = []
    for i, f in enumerate(doc.frames):
        x = (i % cols) * cw
        y = (i // cols) * ch
        imaging.paste(sheet, render.render_frame(doc, f, 1), x, y, blend=False)
        frames_meta.append({"name": f.name, "x": x, "y": y, "w": w, "h": h,
                            "duration": anim.timing(doc)[i]})
    pxa.write_png(out_path, sheet)
    meta = {
        "image": os.path.basename(out_path),
        "size": {"w": cols * cw - padding, "h": rows * ch - padding},
        "frame_size": {"w": w, "h": h},
        "frames": frames_meta,
        "palette": [pxa.format_hex(s.rgba) for s in doc.swatches],
        "meta": dict(doc.meta),
    }
    mp = meta_path or (os.path.splitext(out_path)[0] + ".json")
    with open(mp, "w") as fh:
        json.dump(meta, fh, indent=2)
    return out_path, mp


def gif(doc, out_path, scale=6, fps=None, loop=0, bg=None):
    return anim.to_gif(doc, out_path, scale=scale, fps=fps, loop=loop, bg=bg)


def palette_files(doc, out_dir, name=None):
    name = name or doc.meta.get("name", "palette")
    colors = [s.rgba for s in doc.opaque_swatches()]
    written = [palettes.save_hex(colors, os.path.join(out_dir, "%s.hex" % name))]
    gpl = os.path.join(out_dir, "%s.gpl" % name)
    with open(gpl, "w") as fh:
        fh.write("GIMP Palette\nName: %s\nColumns: 8\n#\n" % name)
        for s in doc.opaque_swatches():
            r, g, b, _ = s.rgba
            fh.write("%3d %3d %3d\t%s\n" % (r, g, b, s.name or pxa.format_hex(s.rgba)))
    written.append(gpl)
    pal_img = imaging.new_image(max(1, len(colors)), 1)
    for i, c in enumerate(colors):
        pal_img[0][i] = c
    written.append(pxa.write_png(os.path.join(out_dir, "%s_palette.png" % name), pal_img, 16))
    return written


def aseprite_script(doc, out_path, png_dir):
    """A Lua script that rebuilds the sprite (frames + palette + timing) inside
    Aseprite, for anyone who wants to keep working by hand."""
    lines = ["-- generated by the pixel-art skill; run: aseprite -b -script this.lua",
             "local spr = Sprite(%d, %d, ColorMode.RGB)" % (doc.width, doc.height),
             "spr.filename = %r" % (doc.meta.get("name", "sprite") + ".aseprite"),
             "local pal = Palette(%d)" % len(doc.swatches)]
    for i, s in enumerate(doc.swatches):
        r, g, b, a = s.rgba
        lines.append("pal:setColor(%d, Color{r=%d,g=%d,b=%d,a=%d})" % (i, r, g, b, a))
    lines.append("spr:setPalette(pal)")
    timings = anim.timing(doc)
    for i, f in enumerate(doc.frames):
        if i > 0:
            lines.append("spr:newEmptyFrame()")
        lines.append("spr.frames[%d].duration = %.3f" % (i + 1, timings[i] / 1000.0))
        lines.append("local img = Image(%d, %d)" % (doc.width, doc.height))
        for y, row in enumerate(f.rows):
            for x, ch in enumerate(row):
                c = doc.rgba(ch)
                if c[3] == 0:
                    continue
                lines.append("img:drawPixel(%d, %d, app.pixelColor.rgba(%d,%d,%d,%d))"
                             % (x, y, c[0], c[1], c[2], c[3]))
        lines.append("spr.cels[%d].image = img" % (i + 1))
    lines.append("spr:saveAs(spr.filename)")
    d = os.path.dirname(os.path.abspath(out_path))
    if d and not os.path.isdir(d):
        os.makedirs(d)
    with open(out_path, "w") as fh:
        fh.write("\n".join(lines) + "\n")
    return out_path


def bundle(doc, out_dir, scales=(1, 2, 4), fps=None, sheet=True, make_gif=None):
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)
    written = []
    written += png(doc, out_dir, scales=scales)
    written += palette_files(doc, out_dir)
    animated = len(doc.frames) > 1
    if sheet and animated:
        sp, mp = spritesheet(doc, os.path.join(out_dir, "%s_sheet.png"
                                               % doc.meta.get("name", "sprite")))
        written += [sp, mp]
    if (make_gif is None and animated) or make_gif:
        written.append(gif(doc, os.path.join(out_dir, "%s.gif" % doc.meta.get("name", "sprite")),
                           scale=max(1, 192 // max(doc.width, doc.height)), fps=fps))
    written.append(aseprite_script(doc, os.path.join(out_dir, "%s.lua"
                                                     % doc.meta.get("name", "sprite")), out_dir))
    return written
